version: "3.8"

services:
  tg_bot:
    build: .
    restart: on-failure
    command: sh -c "python bot.py"
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8001"
    env_file:
      - .env